name       : encryptr
version    : 2.0.0
release    : 2
source     :
    - https://spideroak.com/dist/encryptr/signed/linux/targz/encryptr-2.0.0_amd.tar.gz : 028ff2844ee3c03f900813f24a928a040a588fab091b682f3428abf38e216fc8
license    : GPL-3.0
component  : security
summary    : Encryptr is a zero-knowledge cloud-based password manager
description: |
    Encryptr is a zero-knowledge cloud-based password manager
strip      : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(xtst)
install    : |
    # Install contents
    install -Dm00755 encryptr-bin $installdir/usr/share/encryptr/encryptr-bin
    install -Dm00755 icudtl.dat $installdir/usr/share/encryptr/
    install -Dm00755 libffmpegsumo.so $installdir/usr/share/encryptr/
    install -Dm00755 nw.pak $installdir/usr/share/encryptr/
    # Misc
    install -Dm00755 $pkgfiles/encryptr.sh $installdir/usr/bin/encryptr
    install -Dm00644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/encryptr.png
    install -Dm00644 $pkgfiles/encryptr.desktop $installdir/usr/share/applications/encryptr.desktop
